### ISSUE TITLE
Model Saving Issue when fetched via Relation 

### ISSUE THREAD

**Issue by razorsharpshady** [yidas/codeigniter-model#15]
Few errors occured when I tried to update/save a model which was fetched by relation (hasOne). These are the following **errors** and the code snippet
1. **You must use the "set" method to update an entry. Filename: D:/xyz/system/database/DB_query_builder.php Line Number: 1867**
`$rdf = $paf->rdf;` 
`$rdf->save();`

2. **You must set the database table to be used with your query. Filename: D:/abhishek-phpprojects/RAE-AdminLTE/system/database/DB_query_builder.php Line Number: 1876**
`$rdf = $paf->rdf;` 
`$rdf->id = 1;`
                    `$rdf->first_name = 'Hello';`
`prd($rdf->save());`

3. **last_name field is required** , The "last name" field does contain  the value fetched from database but validation still fails on **required**  validator.
`$rdf = $paf->rdf;`
`$rdf->first_name = 'Hello';`
 `$rdf->save();prd($rdf->getErrors());`

**Comment by yidas** [comment]
Hi @razorsharpshady,

Can you update the library to the last version and try again?

I tested the relation ORM saving and it worked:

```php
$this->load->model('TagsModel');

$tag = $this->TagsModel->findOne(123);
$post = $tag->post;
$post->title = 'Modified from relation';
$post->save();
```

**Comment by yidas** [comment]
You can check and remove `is_unique` validation rule in Model rules, which may cause problem.

**Comment by razorsharpshady** [comment]
Thanks for the quick response,  Updating models works now. 
and what's up with **is_unique**  validator? should I not use it with yidas models?

**Comment by yidas** [comment]
Hi @razorsharpshady,

`is_unique` problem is fixed from [version 2.16.2](https://github.com/yidas/codeigniter-model/releases/tag/2.16.2).

But I don't recommend to use `is_unique` in Model rules because it will be validated at updating.

Cheers!

**Comment by razorsharpshady** [comment]
This error still displays ***You must use the "set" method to update an entry.***
when model is find and saved without modifications.
`$model = $miModel->findOne(5);`
`if($model){`
`$model->save();`
`}`

**Comment by yidas** [comment]
Hi @razorsharpshady,

I tested it and it worked.

```php
$tag = $this->TagsModel->findOne(123);
$tag->save();
```

```php
$tag = $this->TagsModel->findOne(123);
$post = $tag->post;
$post->save();
```

Above two updating without modification is OK.

You can try the last version to check it.

**Comment by razorsharpshady** [comment]
I have checked this on the latest version. 
The `$attributes`  on line **715** are empty in my case which is leading to this error.  
` $sql = $this->_dbr->set($attributes)->get_compiled_update();`

**Comment by yidas** [comment]
Hi @razorsharpshady,

Thanks for your advice.

This issue has been fixed from [version 2.16.3](https://github.com/yidas/codeigniter-model/releases/tag/2.16.3)

Cheers.

**Comment by razorsharpshady** [comment]
Hi @yidas , 
I checked your latest changes in Model.php  
Now it doesn't throw the error but returns **false** if model saved without modifications
```
$model = $miModel->findOne(93);
        var_dump($model->save());exit;
```
which I think is not correct.

**Comment by yidas** [comment]
Hi @razorsharpshady,

You are right!
You can try [version 2.16.4](https://github.com/yidas/codeigniter-model/releases/tag/2.16.4).

Thank you very much!
